# permissions for end users to edit applicationsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: application-set-operator
    app.kubernetes.io/part-of: application-set-operator
    app.kubernetes.io/managed-by: kustomize
  name: applicationset-editor-role
rules:
- apiGroups:
  - web.tutorial.kubebuilder.io
  resources:
  - applicationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.tutorial.kubebuilder.io
  resources:
  - applicationsets/status
  verbs:
  - get
